### ISSUE TITLE
Coinbase - Bollinger Band Trails - Live Trading - ETH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#11] opened 2020-09-17 01:19 UTC
![image](https://user-images.githubusercontent.com/71289772/93408307-4701b880-f862-11ea-90bc-761374ea92a6.png)

**Comment by nibarulabs** [comment] 2020-09-17 14:25
Dupe of #10

**Comment by nibarulabs** [comment] 2020-09-25 20:54
This will be out in 1.1.3. Fixed in code.

**Closed as completed by nibarulabs** 2020-09-25 20:54 UTC
Labels: Coinbase
