### ISSUE TITLE
Coinbase - Bollinger Band Trails - Live Trading - DASH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#13] opened 2020-09-17 01:23 UTC
![image](https://user-images.githubusercontent.com/71289772/93408570-e6bf4680-f862-11ea-9b03-f223e38fe21f.png)

**Comment by nibarulabs** [comment] 2020-09-17 14:26
Dupe of #10

**Comment by nibarulabs** [comment] 2020-09-25 20:54
This will be out in 1.1.3. Fixed in code.

**Closed as completed by nibarulabs** 2020-09-25 20:54 UTC
Labels: Coinbase
