### ISSUE TITLE
Coinbase - Crow EMA Sniper - Live Trading - BCH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#15] opened 2020-09-17 02:19 UTC
![image](https://user-images.githubusercontent.com/71289772/93412187-ae236b00-f86a-11ea-81f2-7b042d9b9daa.png)

**Comment by nibarulabs** [comment] 2020-09-17 14:24
Dupe of #10

**Comment by nibarulabs** [comment] 2020-09-25 20:54
This will be out in 1.1.3. Fixed in code.

**Closed as completed by nibarulabs** 2020-09-25 20:54 UTC
Labels: Coinbase
